{
  "formatVersion": "1.1",
  "component": {
    "url": "../../linked-heap/0.1/linked-heap-0.1.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "linked-heap",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "linked-heap.klib",
          "url": "linked-heap-androidnativex86-0.1.klib",
          "size": 27148,
          "sha512": "1be5ee95a4a04aa50435a4fc7c4db795eddb6a56eaac7e56620fc44cd4ae63d8bf9cc9eff34e51c40200106b0be329815825d3b1b51a96b47b1ba617b0300536",
          "sha256": "64e07b5111de30aef75eae6fc37224622599b228a8a822d8bac46bcc47647bda",
          "sha1": "a404c9a5ab543b655fa8d0893466f6efbbbba915",
          "md5": "77fb86627b21772584ec78b37687e384"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "linked-heap-androidnativex86-0.1-sources.jar",
          "url": "linked-heap-androidnativex86-0.1-sources.jar",
          "size": 3644,
          "sha512": "10bfbf3118806799501c532b62f74ca93bd57cc60c7448e54ba8c42248154176143328d44c6f9c71ba5d4a8614a2eebd47afd6e0cf8440ee9e8149402c3be386",
          "sha256": "50518f77bd130d9e119d0499fc70ad20a920b9efbc91ba2bb6f7dab893cdefa7",
          "sha1": "4ad4769aad2688ee58ba9c95436f9986d04e9453",
          "md5": "50b90e4dc700ad38705c01ba4d044d87"
        }
      ]
    }
  ]
}
