{
  "formatVersion": "1.1",
  "component": {
    "url": "../../linked-heap/0.1/linked-heap-0.1.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "linked-heap",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "linked-heap.klib",
          "url": "linked-heap-linuxarm64-0.1.klib",
          "size": 27147,
          "sha512": "fd2ed393451d613caf46cc147d4209943ecbf37c24c3ec4af9fb67b6e4a4e4125b369a04a41405c99f6872f22e544b0dc17e3c9d23da1fe47ec7b1cd855e9fda",
          "sha256": "fe4424399c0cc415f9a0aaab38cdc5ee950c4fd00a4def31336a3984bdf15f6b",
          "sha1": "38c941bb5ebd5322ea330ebed70437ac5ad85b32",
          "md5": "61dc994988d1d64d46a36cc39772e08f"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "linked-heap-linuxarm64-0.1-sources.jar",
          "url": "linked-heap-linuxarm64-0.1-sources.jar",
          "size": 3644,
          "sha512": "10bfbf3118806799501c532b62f74ca93bd57cc60c7448e54ba8c42248154176143328d44c6f9c71ba5d4a8614a2eebd47afd6e0cf8440ee9e8149402c3be386",
          "sha256": "50518f77bd130d9e119d0499fc70ad20a920b9efbc91ba2bb6f7dab893cdefa7",
          "sha1": "4ad4769aad2688ee58ba9c95436f9986d04e9453",
          "md5": "50b90e4dc700ad38705c01ba4d044d87"
        }
      ]
    }
  ]
}
