{
  "formatVersion": "1.1",
  "component": {
    "url": "../../linked-heap/0.1/linked-heap-0.1.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "linked-heap",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "linked-heap.klib",
          "url": "linked-heap-mingwx64-0.1.klib",
          "size": 27132,
          "sha512": "451041cec40f265eb003417b0eb16e9f69fe35821f71022398e84c5ad50ac7c34d856fd2efa8529747e23eb33f4c2135c5aa94a2678088c695ab079748279a25",
          "sha256": "ae05cf342bd8df4ddc107b38793613f916a22ab8ea836bfb5a662b2a0c3f6a14",
          "sha1": "782b0fa640b2bcbcd2b4846c431b0dfb41721ada",
          "md5": "5414a84fa918720c430ae637ad39bf94"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "linked-heap-mingwx64-0.1-sources.jar",
          "url": "linked-heap-mingwx64-0.1-sources.jar",
          "size": 3644,
          "sha512": "10bfbf3118806799501c532b62f74ca93bd57cc60c7448e54ba8c42248154176143328d44c6f9c71ba5d4a8614a2eebd47afd6e0cf8440ee9e8149402c3be386",
          "sha256": "50518f77bd130d9e119d0499fc70ad20a920b9efbc91ba2bb6f7dab893cdefa7",
          "sha1": "4ad4769aad2688ee58ba9c95436f9986d04e9453",
          "md5": "50b90e4dc700ad38705c01ba4d044d87"
        }
      ]
    }
  ]
}
